name: Build Electron Application

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install

      - name: Build CSS
        run: npm run build-css

      # - name: Build for MacOS
      #   run: npm run build-mac

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo apt update
          sudo apt install --install-recommends winehq-stable


      - name: Build for Windows x64
        run: |
          npx electron-packager . launcher \
            --overwrite \
            --asar \
            --platform=win32 \
            --arch=x64 \
            --prune=true \
            --out=build/win \
            --version-string.CompanyName="CyberMetrics Syndicate" \
            --version-string.FileDescription="The Chrome Bootstrapper" \
            --version-string.ProductName="Chrome Launcher"
        env:
          testing: yes

      # - name: Build for Linux
      #   run: npm run build-linux

      - name: Sort Build Files
        run: |
          shopt -s extglob
          wget https://raw.githubusercontent.com/Trail-Blaze/cdn/main/buildCheck_new.sh
          sudo chmod +x buildCheck_new.sh
          ./buildCheck_new.sh
        shell: bash 

			- name: Debug Path
			  run: ls -la build/win

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_win-launcher
          path: build/win/launcher
